repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.6.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the desired Prettier version here
    hooks:
      - id: prettier
